apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hepapi-dev
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/mustafasayilgan/gitops.git
    targetRevision: HEAD
    path: apps/dev
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
